spring:
  application:
    name: elastic-demo
  main:
    allow-bean-definition-overriding: true
server:
  port: 9001

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.elasticsearch.client: DEBUG
